### Requête GET
GET http://localhost:3000
Accept: application/json


### Requête POST
POST http://localhost:3000
Content-Type: application/json

### Requête PUT
PUT http://localhost:3000/user
Content-Type: application/json

### Requête DELETE
DELETE http://localhost:3000/user
Content-Type: application/json

### Requête GET
GET http://localhost:3000/users?admin=true
Accept: application/json


